### ISSUE TITLE
Separate exported members from unexported members.

### ISSUE THREAD

**Issue by NightRa** [paf31/psc-pages#9]
-||-
See http://functorial.com/psc-pages/docs/Data/Enum/index.html with `floor` for example.
Also, the formatting seems messed up over there:
```
Laws: succ firstEnum >>= succ >>= succ ... succ [cardinality - 1 times] == lastEnum pred lastEnum >>= pred >>= pred ... pred [cardinality - 1 times] == firstEnum
```
=> Lines aren't seperated.
I don't know if it's the docs' or psc-pages' fault.

**Comment by paf31** [comment]
The export issue is fixed.

I think the docs need to be fixed in `Data.Enum`.
